version: '2'

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: localhost
    restart: always
    networks:
      - gitlab-server

    ports:
      - "80:80"
      - "443:443"
      - "23:22"

    volumes:
       - /srv/gitlab/config:/etc/gitlab
       - /srv/gitlab/logs:/var/log/gitlab
       - /srv/gitlab/data:/var/opt/gitlab
       - ./redirect.conf:/etc/nginx/conf.d/redirect.conf

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.teasdale.link'
        postgresql['enable'] =             false
        gitlab_rails['db_username'] =     "postgres"
        gitlab_rails['db_password'] =     "postgres"
        gitlab_rails['db_database'] =     "postgres"
        gitlab_rails['db_host'] =         "postgres"
        gitlab_rails['db_port'] =          5432
        redis['enable'] =                  false
        gitlab_rails['redis_host'] =      "redis"
        gitlab_rails['redis_port'] =       6379

    links:
     - postgres:postgres
     - redis:redis

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - gitlab-server

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
       - /srv/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - gitlab-server

    volumes:
       - /srv/redis/data:/data

networks:
  gitlab-server:
    driver: bridge
