apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: gitlab

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest

        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        - name: ssl
          containerPort: 443

        # Mount all three gitlab volumes into subdirectories of the same pv claim.
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-pvc
          subPath: config
        - mountPath: /var/log/gitlab
          name: gitlab-pvc
          subPath: logs
        - mountPath: /var/opt/gitlab
          name: gitlab-pvc
          subPath: data

        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://gitlab.teasdale.link';
            postgresql['enable'] = false;
            redis['enable'] = false;
            gitlab_rails['db_username'] = "postgres";
            gitlab_rails['db_password'] = "postgres";
            gitlab_rails['db_database'] = "postgres";
            gitlab_rails['db_host'] = "postgres-gitlab";
            gitlab_rails['db_port'] = 5432;
            gitlab_rails['redis_host'] = "redis-gitlab";
            gitlab_rails['redis_port'] = 6379;

      volumes:
        - name: gitlab-pvc
          persistentVolumeClaim:
            claimName: gitlab-persistent-volume-claim  # This matches the persistent volume claim name above

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 22
    targetPort: ssh
    protocol: TCP
    name: ssh
    nodePort: 30002
  - port: 443
    targetPort: ssl
    protocol: TCP
    name: ssl
  selector:
    app: gitlab
