apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-ingress
spec:
  rules:
  - host: gitlab.teasdale.link
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
  - host: st-kube-master
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
